import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";

import MuiWrapper from "components/Wrappers/MuiWrapper";
import Navigation from "components/UI/Navigation/Navigation";
import AuthInitializer from "components/auth/AuthInitializer/AuthInitializer";
import ToastWrapper from "components/Wrappers/ToastWrapper";

const roboto = Roboto({
  display: "swap",
  variable: "--font-roboto",
  subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <MuiWrapper>
          <ToastWrapper>
            <AuthInitializer>
              {children}
              <Navigation />
            </AuthInitializer>
          </ToastWrapper>
        </MuiWrapper>
      </body>
    </html>
  );
}
